Repository tf-encrypted/tf-encrypted, pull requests merged in 2018-10, with the labels that each got.

#204 Extract average prediction time from trace file
  tools/get_avg_prediction_time.py
Labels: in-progress

#203 Odd Implicit Maybe Prime Modulus Tensor
  tensorflow_encrypted/tensor/odd_implicit.py
  tests/test_odd_implicit.py
Labels: in-progress

#192 bit extraction for int100
  examples/inputs.py
  examples/matmul.py
  examples/mnist/run.py
  examples/pond-logreg.py
  examples/securenn/network_a.py
  examples/securenn/network_b.py
  examples/securenn/network_c.py
  examples/securenn/network_d.py
  tensorflow_encrypted/layers/convolution.py
  tensorflow_encrypted/layers/dense.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/__init__.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/prime.py
  tensorflow_encrypted/tensor/shared.py
  tests/test_int100_tensor.py
  tests/test_int32_tensor.py
  tests/test_int64_tensor.py
  tests/test_matmul.py
Labels: in-progress, ready-for-review

#205 memoize decode to avoid adding new nodes to graph whenever called
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/session.py
Labels: in-progress

#206 Fix define private placeholder
  tensorflow_encrypted/protocol/pond.py
Labels: in-progress

#208 Make TFE runnable in python 3.5 again
  tensorflow_encrypted/tensor/tensor.py
Labels: in-progress

#207 Implement a default protocol
  bin/run
  bin/serve
  examples/int32.py
  examples/matmul.py
  tensorflow_encrypted/__init__.py
  tensorflow_encrypted/convert/convert.py
  tensorflow_encrypted/protocol/__init__.py
  tensorflow_encrypted/protocol/protocol.py
  tensorflow_encrypted/session.py
Labels: in-progress

#210 Improve bin/serve to have a configurable batch_size
  bin/serve
  bin/serve_local_cluster
Labels: in-progress

#190 Private compare
  examples/int100.py
  examples/matmul.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/protocol.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/session.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/factory.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/odd_implicit.py
  tensorflow_encrypted/tensor/prime.py
  tensorflow_encrypted/tensor/shared.py
  tensorflow_encrypted/tensor/tensor.py
  tensorflow_encrypted/tensor/utils.py
  tensorflow_encrypted/types.py
  tests/test_int100_tensor.py
  tests/test_lsb.py
  tests/test_odd_implicit.py
  tests/test_pond.py
  tests/test_pond_equal.py
  tests/test_prime_tensor.py
  tests/test_private_compare.py
  tests/test_select_share.py
  tests/test_share.py
Labels: ready-for-review

#214 Private annotation
  Makefile
  bin/run
  bin/serve
  examples/bench_conv2d_sigmoid.py
  examples/convert.py
  examples/export_2inputs_model.py
  examples/federated-average/run.py
  examples/inputs.py
  examples/logreg/data.py
  examples/logreg/tf-logreg.py
  examples/logreg/tfe-logreg.py
  examples/matmul.py
  examples/mnist/run.py
  examples/securenn/network_a.py
  examples/securenn/network_b.py
  examples/securenn/network_c.py
  examples/securenn/network_d.py
  tensorflow_encrypted/__init__.py
  tensorflow_encrypted/convert/convert.py
  tensorflow_encrypted/convert/register.py
  tensorflow_encrypted/io.py
  tensorflow_encrypted/layers/core.py
  tensorflow_encrypted/layers/dense.py
  tensorflow_encrypted/player/__init__.py
  tensorflow_encrypted/protocol/pond.py
  tests/test_convert.py
Labels: in-progress

#216 Require Python 3.5 for development and Circle CI
  .circleci/config.yml
  Makefile
  examples/bench_conv2d_sigmoid.py
  requirements.txt
  setup.py
  tensorflow_encrypted/convert/convert.py
  tests/test_convert.py
Labels: in-progress

#223 Upgrade to tensorflow 1.11.0
  Makefile
  requirements.txt
  setup.py
Labels: in-progress

#221 Batch size + rsqrt
  bin/run
  tensorflow_encrypted/convert/register.py
Labels: in-progress

#226 Fix bug for Morgan and Yann
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/odd_implicit.py
  tensorflow_encrypted/tensor/prime.py
Labels: in-progress

#230 Serve Securenn
  bin/run
  bin/serve
  tensorflow_encrypted/convert/convert.py
  tensorflow_encrypted/session.py
  tools/get_avg_prediction_time.py
Labels: in-progress

#228 Implements reduce_max operation for SecureNN
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/prime.py
  tests/test_reduce_max.py
Labels: ready-for-review

#232 Skip tensorflowcheck on push
  Makefile
Labels: in-progress

#236 Introduce int64 Docker build
  Dockerfile
  Makefile
  requirements.txt
  setup.py
Labels: in-progress

#231 Maxpool
  tensorflow_encrypted/layers/__init__.py
  tensorflow_encrypted/layers/pooling.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/prime.py
  tests/test_maxpool2d.py
Labels: in-progress

#238 Maxpool converter
  tensorflow_encrypted/convert/register.py
  tests/test_convert.py
Labels: in-progress

#233 basic int64 support
  Makefile
  examples/matmul.py
  tensorflow_encrypted/config.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/__init__.py
  tensorflow_encrypted/tensor/fixed.py
  tensorflow_encrypted/tensor/helpers.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/prime.py
  tests/test_batchnorm.py
  tests/test_convolution.py
  tests/test_int100_tensor.py
  tests/test_int32_tensor.py
  tests/test_int64_tensor.py
  tests/test_lsb.py
  tests/test_matmul.py
  tests/test_maxpool2d.py
  tests/test_pond_equal.py
  tests/test_private_compare.py
  tests/test_relu.py
  tests/test_select_share.py
  tests/test_truncate.py
Labels: ready-for-review

#243 Document package renaming
  CHANGELOG.md
Labels: in-progress

#245 Fix CircleCI Tag Filtering
  .circleci/config.yml
Labels: in-progress

#246 Release Branch for 0.2.0-rc0
  CHANGELOG.md
  Makefile
  setup.py
Labels: in-progress

#234 Simplify securenn
  examples/mnist/convert.py
  examples/securenn/network_a.py
  examples/securenn/network_b.py
  examples/securenn/network_c.py
  examples/securenn/network_d.py
  tf_encrypted/config.py
  tf_encrypted/protocol/pond.py
Labels: in-progress

#249 Bump for 0.2.0-rc2
  setup.py
Labels: in-progress

#213 Skeleton structure for docs
  .circleci/config.yml
  .gitignore
  CHANGELOG.md
  DEVELOP.md
  Makefile
  README.md
  docs/source/api/config/config.rst
  docs/source/api/config/local.rst
  docs/source/api/config/remote.rst
  docs/source/api/index.rst
  docs/source/api/layers/avg_pooling_2d.rst
  docs/source/api/layers/batchnorm.rst
  docs/source/api/layers/convolution.rst
  docs/source/api/layers/dense.rst
  docs/source/api/layers/index.rst
  docs/source/api/layers/max_pooling_2d.rst
  docs/source/api/layers/relu.rst
  docs/source/api/layers/reshape.rst
  docs/source/api/layers/sigmoid.rst
  docs/source/api/layers/tanh.rst
  docs/source/api/protocol/index.rst
  docs/source/api/protocol/pond.rst
  docs/source/api/protocol/pond_private_tensor.rst
  docs/source/api/protocol/pond_public_tensor.rst
  docs/source/api/protocol/pond_tensor.rst
  docs/source/api/protocol/protocol.rst
  docs/source/api/protocol/securenn.rst
  docs/source/api/session.rst
  docs/source/conf.py
  docs/source/guides/logistic_regression.rst
  docs/source/guides/mnist.rst
  docs/source/index.rst
  docs/source/usage/getting_started.rst
  docs/source/usage/installation.rst
  img/logo.png
  img/logo_scatter.png
  requirements.txt
  tf_encrypted/__init__.py
  tf_encrypted/config.py
  tf_encrypted/layers/activation.py
  tf_encrypted/layers/batchnorm.py
  tf_encrypted/layers/convolution.py
  tf_encrypted/layers/core.py
  tf_encrypted/layers/dense.py
  tf_encrypted/layers/pooling.py
  tf_encrypted/protocol/pond.py
  tf_encrypted/protocol/protocol.py
  tf_encrypted/protocol/securenn.py
  tf_encrypted/session.py
Labels: ready-for-review

#250 Remove logo from README
  README.md
  img/logo.png
  img/logo_scatter.png
Labels: in-progress

#251 Update setup.py and conf.py for 0.2.0
  docs/source/conf.py
  setup.py
Labels: in-progress

#253 Updates link to paper on arxiv
  README.md
Labels: in-progress

#254 update link to paper in docs
  docs/source/index.rst
Labels: in-progress

#260 more explicit list of contributors
  README.md
Labels: in-progress

#269 upgrade dependencies
  requirements.txt
Labels: ready-for-review
