Repository tf-encrypted/tf-encrypted, pull requests merged in 2018-11, with the labels that each got.

#272 Release 0.3.0 rc0
  CHANGELOG.md
  setup.py
Labels: in-progress

#275 0.3.0-rc1
  RELEASING.md
  docs/source/conf.py
  setup.py
Labels: in-progress

#276 release 0.3.0
  docs/source/conf.py
  setup.py
Labels: in-progress

#280 platform specific
  .circleci/config.yml
  Makefile
Labels: in-progress

#284 fix platform specific build
  .circleci/config.yml
Labels: in-progress

#288 Bug Fix: PondCachedPublicTensor wrong inheritance #287
  tf_encrypted/protocol/pond.py
Labels: in-progress

#281 Fix for private compare bug
  .gitignore
  tests/test_int100_tensor.py
  tests/test_private_compare.py
  tests/test_relu.py
  tests/test_truncate.py
  tf_encrypted/protocol/pond.py
  tf_encrypted/protocol/securenn.py
  tf_encrypted/tensor/int100.py
  tf_encrypted/tensor/tensor.py
Labels: ready-for-review

#292 Typo fix in examples/ files
  examples/mnist/run.py
  examples/securenn/network_a.py
  examples/securenn/network_b.py
  examples/securenn/network_c.py
  examples/securenn/network_d.py
Labels: ready-for-review

#294 Fix macos deploy
  .circleci/config.yml
Labels: in-progress

#295 Update documentation for protocols
  tf_encrypted/__init__.py
  tf_encrypted/protocol/pond.py
  tf_encrypted/protocol/protocol.py
  tf_encrypted/protocol/securenn.py
Labels: ready-for-review

#298 the cache could still fail for linux builds
  .circleci/config.yml
Labels: in-progress

#265 experimental secure random
  .gitignore
  Makefile
  operations/__init__.py
  operations/secure_random/__init__.py
  operations/secure_random/secure_random.cc
  operations/secure_random/test_secure_random.py
  requirements.txt
  setup.py
  tests/test_secure_random.py
  tf_encrypted/__init__.py
  tf_encrypted/convert/register.py
  tf_encrypted/operations/__init__.py
  tf_encrypted/operations/secure_random/__init__.py
  tf_encrypted/operations/secure_random/secure_random.py
Labels: ready-for-review

#303 Add development setup instructions
  .github/CONTRIBUTING.md
  DEVELOP.md
  README.md
Labels: in-progress

#305 dont copy build artifacts when building docker container
  .dockerignore
Labels: ready-for-review

#304 Custom ops tf version
  .circleci/config.yml
  Makefile
  operations/secure_random/test_secure_random.py
  setup.py
  tf_encrypted/operations/secure_random/secure_random.py
Labels: ready-for-review

#306 Adds int64 support for SecureNN
  tests/test_int100_tensor.py
  tests/test_int32_tensor.py
  tests/test_int64_tensor.py
  tests/test_lsb.py
  tests/test_odd_implicit.py
  tests/test_prime_tensor.py
  tests/test_private_compare.py
  tests/test_share.py
  tf_encrypted/config.py
  tf_encrypted/protocol/pond.py
  tf_encrypted/protocol/securenn/__init__.py
  tf_encrypted/protocol/securenn/odd_tensor.py
  tf_encrypted/protocol/securenn/securenn.py
  tf_encrypted/tensor/__init__.py
  tf_encrypted/tensor/int100.py
  tf_encrypted/tensor/int32.py
  tf_encrypted/tensor/int64.py
  tf_encrypted/tensor/prime.py
Labels: ready-for-review

#313 fix error where the build recipe was being run too soon in the bootst…
  Makefile
Labels: in-progress

#312 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: in-progress

#301 randoms without a seed
  operations/secure_random/generators.h
  operations/secure_random/secure_random.cc
  operations/secure_random/test_secure_random.py
  tests/test_secure_random.py
  tf_encrypted/operations/secure_random/__init__.py
  tf_encrypted/operations/secure_random/secure_random.py
Labels: ready-for-review

#314 BatchToSpaceND and SpaceToBatchND
  requirements.txt
  tests/test_batch2space.py
  tf_encrypted/player/__main__.py
  tf_encrypted/player/player.py
  tf_encrypted/protocol/pond.py
  tf_encrypted/tensor/crt.py
  tf_encrypted/tensor/int100.py
  tf_encrypted/tensor/int32.py
  tf_encrypted/tensor/int64.py
  tf_encrypted/tensor/prime.py
Labels: enhancement, ready-for-review

#299 Pad
  tests/test_convert.py
  tests/test_pad.py
  tests/test_zeros.py
  tf_encrypted/convert/register.py
  tf_encrypted/protocol/pond.py
Labels: in-progress

#317 add batch2space and space2batch conversion tests
  tests/test_convert.py
  tf_encrypted/convert/register.py
Labels: ready-for-review

#316 secure random numbers everywhere
  tf_encrypted/protocol/securenn/odd_tensor.py
  tf_encrypted/tensor/crt.py
  tf_encrypted/tensor/int32.py
  tf_encrypted/tensor/int64.py
  tf_encrypted/tensor/prime.py
Labels: in-progress

#319 fix batch2space tests precision for int64 support
  tests/test_batch2space.py
Labels: in-progress

#315 release 0.4.0 rc0
  CHANGELOG.md
  README.md
  docs/source/conf.py
  setup.py
Labels: ready-for-review

#321 fix version rc1
  docs/source/conf.py
  setup.py
Labels: in-progress

#323 use project email
  .github/CONTRIBUTING.md
Labels: in-progress

#322 release 0.4.0-rc2
  Makefile
  README.md
  docs/source/conf.py
  setup.py
Labels: ready-for-review

#324 Add argmax support to SecureNN
  tests/test_argmax.py
  tf_encrypted/protocol/securenn/securenn.py
Labels: in-progress

#325 fix rejection sampling, call the correct subclass method
  Makefile
  operations/secure_random/generators.h
  operations/secure_random/secure_random.cc
  tests/test_secure_random.py
Labels: ready-for-review

#331 Clean up conversion tests
  tests/test_convert.py
  tests/test_pad.py
  tf_encrypted/convert/register.py
Labels: ready-for-review

#328 argmax converter
  tests/test_convert.py
  tf_encrypted/convert/register.py
Labels: ready-for-review
