Repository tf-encrypted/tf-encrypted, pull requests merged in 2018-09, with the labels that each got.

#88 fix python gcp scripts
  tools/gcp/link
  tools/gcp/serve
Labels: in progress, ready-for-review

#98 Fix config
  bin/serve
  examples/mnist/README.md
  examples/mnist/run.py
  tensorflow_encrypted/config.py
Labels: in progress, ready-for-review

#99 Improve mypy support
  Makefile
  stubs/tensorflow/__init__.pyi
  stubs/tensorflow/train/__init__.pyi
  tensorflow_encrypted/player/__main__.py
  tensorflow_encrypted/tensor/int32.py
Labels: in progress, ready-for-review

#102 few suggestions
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
Labels: in progress, ready-for-review

#103 Safe truncate
  tensorflow_encrypted/__init__.py
  tensorflow_encrypted/player/__init__.py
  tensorflow_encrypted/player/player.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
  tests/test_truncate.py
Labels: in progress, ready-for-review

#95 fixes crt overflow error by splitting matmul in smaller matmuls in th…
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
  tests/test_big_matmul.py
Labels: ready-for-review

#104 Update MNIST example to use slightly newer IO api
  examples/mnist/README.md
  examples/mnist/run.py
Labels: in progress, ready-for-review

#107 Make PondTensor abstract
  tensorflow_encrypted/protocol/pond.py
Labels: in progress, ready-for-review

#108 setting the stage
  examples/securenn-playground.py
  tensorflow_encrypted/protocol/__init__.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/protocol.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/int100.py
  tests/test_truncate.py
Labels: in progress, ready-for-review

#109 native tensor
  examples/int100.py
  stubs/tensorflow/__init__.pyi
  tensorflow_encrypted/io.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/__init__.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/native.py
Labels: in progress, ready-for-review

#111 First steps for SecureNN
  examples/securenn-playground.py
  tensorflow_encrypted/protocol/__init__.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/protocol.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/int100.py
  tests/test_truncate.py
Labels: in progress, ready-for-review

#110 Publish releases to pypi
  Makefile
  README.md
  RELEASING.md
  setup.py
Labels: in progress, ready-for-review

#119 link README badges to real content rather than the image
  README.md
Labels: in progress, ready-for-review

#120 native binarize and some more tests around native tensors
  stubs/tensorflow/__init__.pyi
  tensorflow_encrypted/tensor/native.py
  tests/test_native_tensor.py
Labels: in progress, ready-for-review

#116 Improve serving
  bin/serve
  bin/serve_local_cluster
  docker-compose.yml
  requirements.txt
  tensorflow_encrypted/config.py
Labels: in progress, ready-for-review

#122 __getitem__ with tests
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/native.py
  tests/test_native_tensor.py
Labels: in progress, ready-for-review

#121 Gcp readme
  examples/mnist/README.md
  tools/gcp/README.md
Labels: in progress, ready-for-review

#125 Update setup.py for 0.1.0-rc0 release
  setup.py
Labels: ready-for-review

#114 Fix code snippet in README
  README.md
Labels: in progress, ready-for-review

#127 Update setup.py for 0.1.0
  setup.py
Labels: ready-for-review

#115 Updates for Int32 tensor
  examples/int32.py
  examples/mnist/README.md
  examples/pond-simple.py
  examples/securenn/README.md
  examples/securenn/network_a.py
  tensorflow_encrypted/config.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
Labels: in progress, ready-for-review

#129 Getting started guide
  README.md
  docs/getting_started.md
  docs/images/model.png
  docs/images/modelTrainer_PredictionClient.png
  docs/images/pond.png
  docs/images/tf_layers.png
  docs/images/tfe_layers.png
  examples/mnist_deep_cnn.py
  examples/test_data/mnist_input.npy
  examples/test_data/mnist_model.pb
Labels: ready-for-review

#138 add a note to run tools/gcp commands from that directory
  tools/gcp/README.md
Labels: ready-for-review

#142 remove images from the getting started document
  docs/getting_started.md
  docs/images/model.png
  docs/images/modelTrainer_PredictionClient.png
  docs/images/pond.png
  docs/images/tf_layers.png
  docs/images/tfe_layers.png
Labels: ready-for-review

#143 fixed links in the contents of the getting started doc
  docs/getting_started.md
Labels: ready-for-review

#144 add Tanh
  tensorflow_encrypted/layers/activation.py
  tensorflow_encrypted/protocol/pond.py
  tests/test_tanh.py
Labels: ready-for-review

#147 Bugfix for masked conv2d in pond
  tensorflow_encrypted/protocol/pond.py
Labels: ready-for-review

#132 added an alpha badge to the README
  README.md
Labels: ready-for-review

#155 Concat
  tensorflow_encrypted/convert/register.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/protocol.py
  tests/test_concat.py
Labels: ready-for-review

#158 Implement select share (secureNN) (#154)
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/securenn.py
  tests/test_select_share.py
Labels: ready-for-review

#128 introduce a factory pattern for creating tensors inside of a protocol
  stubs/tensorflow/__init__.pyi
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/protocol.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/factory.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/native.py
  tensorflow_encrypted/tensor/tensor.py
Labels: ready-for-review

#163 quick fix for broken tests
  tests/test_native_tensor.py
Labels: ready-for-review

#151 Hack: logreg training example
  examples/logreg/data.py
  examples/logreg/tf-logreg.py
  examples/logreg/tfe-logreg.py
  stubs/tensorflow/__init__.pyi
  tensorflow_encrypted/protocol/pond.py
Labels: ready-for-review

#169 Add matmul alias
  tensorflow_encrypted/protocol/pond.py
  tests/test_big_matmul.py
  tests/test_matmul.py
Labels: ready-for-review

#166 int 32 binarize
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/native.py
  tests/test_int32_tensor.py
Labels: ready-for-review

#170 return all of the bits for binarize on int32
  tensorflow_encrypted/tensor/int32.py
  tests/test_int32_tensor.py
Labels: ready-for-review

#171 rename native tensor to prime tensor
  tensorflow_encrypted/tensor/__init__.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/native.py
  tensorflow_encrypted/tensor/prime.py
  tests/test_native_tensor.py
  tests/test_prime_tensor.py
Labels: ready-for-review

#172 int64 plus other improvements for shared functions
  stubs/tensorflow/__init__.pyi
  stubs/tensorflow/bitwise/__init__.pyi
  tensorflow_encrypted/tensor/__init__.py
  tensorflow_encrypted/tensor/factory.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/native_shared.py
  tensorflow_encrypted/tensor/prime.py
  tensorflow_encrypted/tensor/tensor.py
  tests/test_int32_tensor.py
  tests/test_prime_tensor.py
Labels: ready-for-review

#174 124 threads
  bin/serve
Labels: ready-for-review

#173 Python35
  README.md
  setup.py
  tensorflow_encrypted/config.py
  tensorflow_encrypted/convert/convert.py
  tensorflow_encrypted/layers/activation.py
  tensorflow_encrypted/layers/batchnorm.py
  tensorflow_encrypted/layers/convolution.py
  tensorflow_encrypted/layers/core.py
  tensorflow_encrypted/layers/pooling.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/protocol.py
  tensorflow_encrypted/protocol/securenn.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/helpers.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/prime.py
Labels: ready-for-review

#176 name scope binarize function
  tensorflow_encrypted/tensor/native_shared.py
Labels: ready-for-review

#178 Fix Converter
  tensorflow_encrypted/convert/convert.py
  tensorflow_encrypted/convert/register.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
Labels: ready-for-review

#177 implement a shared conv2d for int32 and int64
  examples/int100.py
  stubs/tensorflow/__init__.pyi
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/native_shared.py
  tests/test_int32_tensor.py
  tests/test_int64_tensor.py
Labels: ready-for-review

#187 Remove rsqrt
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
Labels: ready-for-review

#185 Extract reduce_sum contribution
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
  tests/test_reduce_sum.py
Labels: ready-for-review

#186 use shared conv2d for int100 as well
  tensorflow_encrypted/tensor/__init__.py
  tensorflow_encrypted/tensor/crt.py
  tensorflow_encrypted/tensor/int100.py
  tensorflow_encrypted/tensor/int32.py
  tensorflow_encrypted/tensor/int64.py
  tensorflow_encrypted/tensor/shared.py
  tests/test_int32_tensor.py
  tests/test_int64_tensor.py
Labels: ready-for-review

#195 Add a default configuration
  bin/serve
  examples/logreg/data.py
  examples/logreg/tf-logreg.py
  examples/logreg/tfe-logreg.py
  tensorflow_encrypted/__init__.py
  tensorflow_encrypted/config.py
  tensorflow_encrypted/protocol/pond.py
  tensorflow_encrypted/protocol/securenn.py
Labels: ready-for-review

#197 Add bias
  tensorflow_encrypted/convert/register.py
Labels: in-progress
