Repository tf-encrypted/tf-encrypted, pull requests merged in 2019-06, with the labels that each got.

#553 Improved project description
  README.md
Labels: ready-for-review

#571 Convert tf.keras into tfe.keras model
  examples/notebooks/a - Secure Classification with TFE Keras - Public Training.ipynb
  examples/notebooks/b - Secure Classification with TFE Keras - Secure Model Serving .ipynb
  examples/notebooks/c - Secure Classification with TFE Keras - Private Prediction Client.ipynb
  tf_encrypted/keras/engine/base_layer.py
  tf_encrypted/keras/layers/convolutional.py
  tf_encrypted/keras/layers/dense.py
  tf_encrypted/keras/models/__init__.py
  tf_encrypted/keras/models/sequential.py
  tf_encrypted/keras/models/sequential_test.py
Labels: in-progress

#584 make sure tfe.keras.layers use same tf.keras.layers default args
  tf_encrypted/keras/engine/base_layer.py
  tf_encrypted/keras/layers/convolutional.py
  tf_encrypted/keras/layers/dense.py
  tf_encrypted/keras/layers/layers_utils.py
  tf_encrypted/keras/layers/normalization.py
  tf_encrypted/keras/layers/relu.py
  tf_encrypted/keras/models/sequential_test.py
  tf_encrypted/keras/testing_utils.py
Labels: in progress
